on:
  push

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate SBOM and Upload
      id: tdb-tests
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_service: ekrem-test-app-2
        dd_env: ci
        dd_site: datad0g.com
